lib/chess_web/router.ex
defmodule ChessWeb.Router do
  use ChessWeb, :router

  alias Phoenix.Token

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(Chess.Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
    plug(:put_user_token)
  end

  pipeline :api do
    plug(:fetch_session)
    plug(:accepts, ["json"])
  end

  scope "/", ChessWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    resources("/session", SessionController, only: [:new, :create, :delete], singleton: true)
    resources("/registration", RegistrationController, only: [:new, :create], singleton: true)
  end

  scope "/", ChessWeb do
    pipe_through([:browser, :auth, :ensure_auth])

    resources("/games", GameController, only: [:index, :new, :create, :show, :delete])
    resources("/profile", ProfileController, only: [:edit, :update], singleton: true)
    resources("/password", PasswordController, only: [:edit, :update], singleton: true)
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  defp put_user_token(conn, _) do
    if current_user = Guardian.Plug.current_resource(conn) do
      token = Token.sign(conn, "game socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
end

web/router.ex
defmodule Chess.Router do
  use Chess.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chess do
    pipe_through :browser # Use the default browser stack

    get "/", GameController, :index
    resources "/games", GameController, only: [:create, :show, :delete]
  end

  # Other scopes may use custom stacks.
  scope "/api", Chess do
    pipe_through :api

    resources "/games", Api.GameController, only: [:show, :update]
  end
end

lib/chess_web/controllers/profile_controller.ex
defmodule ChessWeb.ProfileController do
  @moduledoc false

  use ChessWeb, :controller

  import Chess.Auth, only: [current_user: 1]

  alias Chess.Store.User

  def edit(conn, _params) do
    changeset = User.changeset(current_user(conn), %{})

    conn
    |> render("edit.html", changeset: changeset)
  end

  def update(conn, %{"user" => user}) do
    changeset = User.profile_changeset(current_user(conn), user)

    case Repo.update(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, gettext("Profile updated successfully."))
        |> redirect(to: page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end
end

lib/chess_web/views/profile_view.ex
defmodule ChessWeb.ProfileView do
  use ChessWeb, :view
end

lib/chess_web/templates/profile/edit.html.eex
<div class="form">
  <h2><%= gettext "Profile" %></h2>

  <%= form_for @changeset, profile_path(@conn, :update), [class: "update-profile", novalidate: true], fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>
          <%= gettext "Oops, something went wrong! Please check the errors below." %>
        </p>
      </div>
    <% end %>

    <div class="form-group">
      <div class="form-field">
        <%= input f, :name %>
      </div>
      <div class="form-field">
        <%= input f, :email, as: :email %>
      </div>
      <div class="form-field">
        <%= link gettext("Change password"), to: password_path(@conn, :edit) %>
      </div>
    </div>
    <div class="form-group">
      <%= submit gettext("Update Profile"), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>