lib/chess_web/router.ex
defmodule ChessWeb.Router do
  use ChessWeb, :router

  alias Phoenix.Token

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(Chess.Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
    plug(:put_user_token)
  end

  pipeline :api do
    plug(:fetch_session)
    plug(:accepts, ["json"])
  end

  scope "/", ChessWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    resources("/session", SessionController, only: [:new, :create, :delete], singleton: true)
    resources("/registration", RegistrationController, only: [:new, :create], singleton: true)
  end

  scope "/", ChessWeb do
    pipe_through([:browser, :auth, :ensure_auth])

    resources("/games", GameController, only: [:index, :new, :create, :show, :delete])
    resources("/profile", ProfileController, only: [:edit, :update], singleton: true)
    resources("/password", PasswordController, only: [:edit, :update], singleton: true)
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  defp put_user_token(conn, _) do
    if current_user = Guardian.Plug.current_resource(conn) do
      token = Token.sign(conn, "game socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
end

web/router.ex
defmodule Chess.Router do
  use Chess.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chess do
    pipe_through :browser # Use the default browser stack

    get "/", GameController, :index
    resources "/games", GameController, only: [:create, :show, :delete]
  end

  # Other scopes may use custom stacks.
  scope "/api", Chess do
    pipe_through :api

    resources "/games", Api.GameController, only: [:show, :update]
  end
end

lib/chess_web/views/layout_view.ex
defmodule ChessWeb.LayoutView do
  use ChessWeb, :view

  import Chess.Auth, only: [current_user: 1]
end

lib/chess_web/templates/layout/_alerts.html.eex
<div class="container alerts">
  <p class="alert alert--info" role="alert">
    <%= get_flash(@conn, :info) %>
  </p>
  <p class="alert alert--danger" role="alert">
    <%= get_flash(@conn, :error) %>
  </p>
</div>

lib/chess_web/templates/layout/_head.html.eex
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="csrf-token" content="<%= Plug.CSRFProtection.get_csrf_token() %>" />

  <title><%= gettext "64squares" %></title>
  <link href="https://fonts.googleapis.com/css?family=Enriqueta:400,700" rel="stylesheet">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

lib/chess_web/templates/layout/_header.html.eex
<header class="header" role="banner">
  <div class="container">
    <h1 class="header__title">
      <%= link gettext("64squares"), to: page_path(@conn, :index) %>
    </h1>

    <nav class="header__user-nav" role="user">
      <%= if current_user(@conn) do %>
        <%= link(current_user(@conn).name, to: profile_path(@conn, :edit)) %>
        (<%= current_user(@conn).email %>)
        |
        <%= link gettext("Log out"),
                 to: session_path(@conn, :delete),
                 method: :delete %>
      <% else %>
        <%= link gettext("Register"), to: registration_path(@conn, :new) %>
        |
        <%= link gettext("Log in"), to: session_path(@conn, :new) %>
      <% end %>
    </nav>
  </div>
</header>

lib/chess_web/templates/layout/_scripts.html.eex
<script>window.userToken = "<%= @token %>";</script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

lib/chess_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "_head.html", conn: @conn %>

  <body>
    <%= render "_header.html", conn: @conn %>
    <%= render "_alerts.html", conn: @conn %>

    <main role="main">
      <div class="container">
        <%= @inner_content %>
      </div>
    </main>

    <%= render "_scripts.html", conn: @conn, token: assigns[:user_token] %>
  </body>
</html>